---
# Removes the generated key from Github
- name: Revoke Github deploy key
  uri:
    url: "{{ github_api_deploy_key_delete_url }}/{{ github_api_deploy_key_id }}"
    method: DELETE
    HEADER_Authorization: "token {{ github_deploy_api_token | mandatory }}"
    body_format: json
    status_code: 204
    return_content: yes
  register: github_api_deploy_key_delete_response
  run_once: yes
  delegate_to: "{{ github_deploy_local_delegate }}"

# Deletes the transient private key from the host
- name: Delete the transient deploy key host temp dir
  file:
    path: "{{ github_deploy_key_temp_dir }}"
    state: absent
...
